services:
  meta-swap-api:
    image: superioragents/meta-swap-api
    build:
      context: meta-swap-api
      dockerfile: Dockerfile
    ports:
      - "${TRADE_API_PORT:-9009}:${TRADE_API_PORT:-9009}"
    restart: unless-stopped

secrets:
  meta-swap-api:
    file: meta-swap-api/.env
    
