name: 🎲 Misc/random discussions that do not fit into the above categories.
description: Submit a discussion as you like.
title: "[Misc]: "
labels: ["misc"]

body:
  - type: markdown
    attributes:
      value: >
        #### Before submitting an issue, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/SuperiorAgents/superior-agents/issues?q=is%3Aissue%20state%3Aopen%20sort%3Acreated-desc).
  - type: textarea
    attributes:
      label: Anything you want to discuss about SuperiorAgents.
      description: >
        Anything you want to discuss about SuperiorAgents.
    validations:
      required: true
  - type: markdown
    attributes:
      value: >
        Thanks for contributing 🎉!
